# Site settings
title: Design Portfolio
email: sayedakbarali1972@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Freelance web designer and developer, specialising with jekyll,
 Html, CSS and description
baseurl: "/ttStatic" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: sayed
github_username: sayed
google_username: sayed

permalink: /:categories/:title

links:
 - title: about
   url: /about
 - title: work
   url: /work
 - title: articles
   url: /articles
 - title: hire me
   url: /hire me




# Build settings
markdown: kramdown
